Revert "Update to Tokio 1.0"
This reverts commit cdfbb1294ddc1cc6148c5e2c1abfb0d8610e0a84.

I am seeing the message:

```
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime
```

When trying to connect and I think it's because of this.